# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
